version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: restaurant_web_prod
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings_prod
    env_file:
      - .env.prod
    ports:
      - "80:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  static_volume:
  media_volume: