version: '3.8'

# Simplified production setup without SSL complications
# For debugging nginx issues and ensuring basic functionality

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.ec2
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./.env.ec2:/app/.env.ec2
      - ./frontend/dist:/app/frontend_static
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings_ec2
    env_file:
      - .env.ec2
    restart: unless-stopped
    networks:
      - restaurant_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/var/www/html:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - restaurant_network

networks:
  restaurant_network:
    driver: bridge