version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.ec2
    volumes:
      - ./data:/app/data
      - ./.env.ec2:/app/.env.ec2
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings_ec2
    env_file:
      - .env.ec2
    restart: unless-stopped
    networks:
      - restaurant_network
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/html
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - restaurant_network

networks:
  restaurant_network:
    driver: bridge