# Docker Compose for EC2 + SQLite + Docker Production Deployment
version: '3.8'

services:
  # Main Django Application
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.ec2
    container_name: restaurant_web_ec2
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings_ec2
    ports:
      - "8000:8000"
    volumes:
      # Persistent data volume for SQLite database
      - restaurant_data:/app/data
      # Logs volume
      - restaurant_logs:/app/logs
      # Static files volume (for serving via nginx if needed)
      - restaurant_static:/app/staticfiles
      # Media files volume
      - restaurant_media:/app/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "manage.py", "check", "--deploy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Optional: Nginx reverse proxy for static files
  nginx:
    image: nginx:alpine
    container_name: restaurant_nginx_ec2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - restaurant_static:/usr/share/nginx/html/static
      - restaurant_media:/usr/share/nginx/html/media
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: unless-stopped
    profiles:
      - nginx  # Optional service - activate with --profile nginx

# Persistent volumes for data persistence across deployments
volumes:
  restaurant_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/restaurant-app/data
  restaurant_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/restaurant-app/logs
  restaurant_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/restaurant-app/staticfiles
  restaurant_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/restaurant-app/media

# Networks
networks:
  default:
    name: restaurant_network