version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.ec2
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - static_volume:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings_ec2
      - DEBUG=0
      - ALLOWED_HOSTS=*
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - restaurant_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/static
      - ./frontend/dist:/var/www/html
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - restaurant_network

volumes:
  static_volume:

networks:
  restaurant_network:
    driver: bridge