#version: "3.9"

services:
  db:
    image: postgres:17-alpine
    container_name: cnt_restaurant_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # Configuración clave para PostgreSQL 17
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: America/Lima
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cnt_restaurant_web
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - .:/home/django/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
